source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PMEasyCamera_Example', :exclusive => true do
  pod "PMEasyCamera", :path => "../"
  pod 'ESCObservable'
  pod 'ASYPresenterSupport'

end

target 'PMEasyCamera_Tests', :exclusive => true do
  pod "PMEasyCamera", :path => "../"

  
end

post_install do |installer|
  installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
    configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
  end
end
