# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'PMEasyCameraDemo' do
  pod 'ESCObservable'
  pod 'ASYPresenterSupport'
end

target 'PMEasyCameraDemoTests' do

end

target 'PMEasyCameraDemoUITests' do

end

